name: CI

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

  workflow_dispatch:

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: assignment-basic
        run: |
          pnpm install
          pnpm -F assignment test:basic
  advanced:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: assignment-advanced
        run: |
          pnpm install
          pnpm -F assignment test:advanced
